general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
       org: 'fc73fe23trial'
       space: 'dev'
       credentialsId: 'CF_CREDENTIALSID'
       apiEndpoint: 'https://api.cf.us10.hana.ondemand.com'
       verbose: true
