general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
       org: '46172fdf-b63a-4ffd-ae59-7de16e2fa184'
       space: 'dev'
       credentialsId: 'CF_CREDENTIALSID'
